//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbstractAutoTransactions
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DefaultAmount { get; set; }
        public int AbstractCategoryId { get; set; }
        public int BudgetId { get; set; }
        public int DayOfTheMonth { get; set; }
        public string LastPaymentDate { get; set; }
        public bool Active { get; set; }
    }
}
