//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalanceAdmin_Entities : DbContext
    {
        public BalanceAdmin_Entities()
            : base("name=BalanceAdmin_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbstractCategory> AbstractCategory { get; set; }
        public virtual DbSet<AbstractIncome> AbstractIncome { get; set; }
        public virtual DbSet<BudgetAutoTransaction> BudgetAutoTransaction { get; set; }
        public virtual DbSet<BudgetGroup> BudgetGroup { get; set; }
        public virtual DbSet<BudgetMonth> BudgetMonth { get; set; }
        public virtual DbSet<BudgetTransaction> BudgetTransaction { get; set; }
        public virtual DbSet<IncomeTransaction> IncomeTransaction { get; set; }
        public virtual DbSet<BalanceCheckPoint> BalanceCheckPoint { get; set; }
    }
}
