//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetTransaction
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }
        public int AbstractCatrgoryId { get; set; }
        public int BudgetMonthId { get; set; }
        public Nullable<int> BudgetAutoTransactionId { get; set; }
    }
}
