//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeTransaction
    {
        public int Id { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Name { get; set; }
        public Nullable<int> AbstractIncomeId { get; set; }
        public Nullable<int> BudgetMonthId { get; set; }
    
        public virtual AbstractIncome AbstractIncome { get; set; }
        public virtual BudgetMonth BudgetMonth { get; set; }
    }
}
