//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Legacy_prodEntities : DbContext
    {
        public Legacy_prodEntities()
            : base("name=Legacy_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbstractAutoTransactions> AbstractAutoTransactions { get; set; }
        public virtual DbSet<AbstractCategories> AbstractCategories { get; set; }
        public virtual DbSet<BudgetForMonth> BudgetForMonth { get; set; }
        public virtual DbSet<BudgetIncomes> BudgetIncomes { get; set; }
        public virtual DbSet<BudgetItemGroup> BudgetItemGroup { get; set; }
        public virtual DbSet<BudgetItemLog> BudgetItemLog { get; set; }
        public virtual DbSet<BudgetItems> BudgetItems { get; set; }
        public virtual DbSet<DbBackUpLog> DbBackUpLog { get; set; }
        public virtual DbSet<FinandaSyncLog> FinandaSyncLog { get; set; }
        public virtual DbSet<FinandaTransactions> FinandaTransactions { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<SystemMessages> SystemMessages { get; set; }
        public virtual DbSet<TransactionCheckPoint> TransactionCheckPoint { get; set; }
    }
}
