//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBalanceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMessages
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string ExtraData { get; set; }
        public string IType { get; set; }
        public System.DateTime Date { get; set; }
        public bool SendMail { get; set; }
    }
}
